<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ADOE-20150303CS" ignored="0" name="Test" tests="19" failures="1" timestamp="07 十一月 2018 05:31:22 GMT" time="5.805" errors="0">
  <testcase name="f" time="1.451" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.247" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.198" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.138" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.215" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.176" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.143" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.223" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.142" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.858" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.179" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.154" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.15" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.135" classname="com.yy.test.NewTest"/>
  <testcase name="test1" time="0.007" classname="com.yy.test.NewTest"/>
  <testcase name="test2" time="0.002" classname="com.yy.test.NewTest"/>
  <testcase name="test3" time="0.004" classname="com.yy.test.NewTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.009" classname="com.yy.test.NewTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.002" classname="com.yy.test.NewTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
	at com.yy.test.NewTest.test3(NewTest.java:36)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test -->
